### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by eduardokraus** [gerencianet/gn-lightbox-example#2]
Ao executar o index.html no console aparece o seguinte erro:

`Uncaught ReferenceError: $gn is not defined at script.js:1`

**Comment by tiagoxpl** [comment]
@eduardokraus 

Isso ocorre pois é necessário que você gere o código Javascript, específico de sua conta, e substitua pelo que está atualmente no arquivo index no bloco <head>. Para tal, você deverá informar o seu "identificador de conta" Gerencianet para obter o código. Para obter, acesse: https://dev.gerencianet.com.br/docs/checkout-ligthbox

Qualquer questão, a Gerenciane está à disposição para auxiliá-lo.
